OPTIONS (ERRORS=0)
LOAD DATA TRUNCATE
INTO TABLE M_HOLIDAY
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  HOLIDAY_DATE "TO_CHAR(TO_DATE(:HOLIDAY_DATE,'YYYY/MM/DD'),'YYYY/MM/DD')"
, HOLIDAY_NAME
)
