OPTIONS (ERRORS=0)
LOAD DATA TRUNCATE
INTO TABLE SYS_BAT_PARM
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(PROGRAM_CD, FUNCTION_NAME, BUSINESS_GROUP_CD, BUSINESS_CD, FILE_PATH, FILE_NAME, LOG_MODE_TYP, OUTPUT_MODE_TYP)
