<%
/*------------------------------------------------------------------------------
UZ2020.inc

2004/01/15 V‹Kì¬  K.Shiraki
------------------------------------------------------------------------------*/
%>
<script language="JavaScript" src="common/AZ0040vector.js"></script>
<script language="JavaScript" src="common/AZ0040tablemodel.js"></script>
<script language="JavaScript" src="common/AZ0040common.js"></script>
<link rel="stylesheet" href="common/AZ0040.css">
