<%
/*------------------------------------------------------------------------------
AZ0050.inc

2004/01/15 新規作成  K.Shiraki
2009/12/20 一般検索-条件の値「両方と一致する」の日本語固定を多言語化
------------------------------------------------------------------------------*/
%>
<%  String jsFileName2 = "AZ0050common_" + locale + ".js"; %>
<script language="JavaScript" src="common/AZ0050vector.js"></script>
<script language="JavaScript" src="common/AZ0050tablemodel.js"></script>
<script language="JavaScript" src="common/<%=jsFileName2%>"></script>
<link rel="stylesheet" href="common/AZ0050.css">
