CREATE OR REPLACE VIEW M_PLANT_VEND_CTRL (
     COMPANY_CD
    ,VEND_CD
    ,CUST_COMPANY_CD
    ,CUST_CD
) AS
SELECT null AS COMPANY_CD
      ,null AS VEND_CD
      ,null AS CUST_COMPANY_CD
      ,null AS CUST_CD
FROM   DUAL
/
COMMENT ON TABLE M_PLANT_VEND_CTRL                    IS '工場間取引定義ビュー'
/
COMMENT ON COLUMN M_PLANT_VEND_CTRL.COMPANY_CD        IS '会社コード'
/
COMMENT ON COLUMN M_PLANT_VEND_CTRL.VEND_CD           IS '取引先コード'
/
COMMENT ON COLUMN M_PLANT_VEND_CTRL.CUST_COMPANY_CD   IS '得意先会社コード'
/
COMMENT ON COLUMN M_PLANT_VEND_CTRL.CUST_CD           IS '得意先コード'
/
