CREATE OR REPLACE VIEW M_SALES_UNIT_COST (
     COMPANY_CD
    ,CUST_CD
    ,ITEM_CD
    ,PURPOSE_UNIT_PRICE_TYP
    ,EFF_PHASE_IN_DATE
    ,SALES_UNIT_SIZE
    ,SALES_UNIT_COST
    ,UNIT_COST_TYP
) AS
SELECT   COMPANY_CD
        ,CUST_CD
        ,ITEM_CD
        ,1                  AS PURPOSE_UNIT_PRICE_TYP
        ,EFF_PHASE_IN_DATE
        ,0                  AS SALES_UNIT_SIZE
        ,UNIT_COST          AS SALES_UNIT_COST
        ,UNIT_COST_TYP
FROM    M_UNIT_COST
/
COMMENT ON TABLE M_SALES_UNIT_COST                    IS '販売単価ビュー'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.COMPANY_CD        IS '会社コード'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.CUST_CD           IS '得意先コード'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.ITEM_CD           IS '品目番号'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.PURPOSE_UNIT_PRICE_TYP IS '用途別単価区分'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.EFF_PHASE_IN_DATE IS '販売単価有効開始日'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.SALES_UNIT_SIZE   IS 'サイズ'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.SALES_UNIT_COST   IS '販売単価'
/
COMMENT ON COLUMN M_SALES_UNIT_COST.UNIT_COST_TYP     IS '単価区分'
/
