CREATE OR REPLACE VIEW M_SCM_COMPANY (
    COMPANY_CD
   ,COMPANY_FNAME
   ,COMPANY_NAME
   ,COMPANY_KNAME
   ,COMPANY_ENAME
   ,ZIP_CD
   ,ADDRESS_1
   ,ADDRESS_2
   ,ADDRESS_K_1
   ,ADDRESS_K_2
   ,TEL
   ,FAX
) AS
SELECT       
    COMPANY_CD AS COMPANY_CD
   ,''         AS COMPANY_FNAME
   ,''         AS COMPANY_NAME
   ,''         AS COMPANY_KNAME
   ,''         AS COMPANY_ENAME
   ,''         AS ZIP_CD
   ,''         AS ADDRESS_1
   ,''         AS ADDRESS_2
   ,''         AS ADDRESS_K_1
   ,''         AS ADDRESS_K_2
   ,''         AS TEL
   ,''         AS FAX
FROM    SYS_MY_COMPANY
WHERE   CTRL_CD = 'SYSTEM'
/
COMMENT ON TABLE M_SCM_COMPANY                 IS '会社ビュー'
/
COMMENT ON COLUMN M_SCM_COMPANY.COMPANY_CD     IS '会社コード'
/
COMMENT ON COLUMN M_SCM_COMPANY.COMPANY_FNAME  IS '会社正式名'
/
COMMENT ON COLUMN M_SCM_COMPANY.COMPANY_NAME   IS '会社名'
/
COMMENT ON COLUMN M_SCM_COMPANY.COMPANY_KNAME  IS '会社名（カナ）'
/
COMMENT ON COLUMN M_SCM_COMPANY.COMPANY_ENAME  IS '会社名（英名）'
/
COMMENT ON COLUMN M_SCM_COMPANY.ZIP_CD         IS '郵便番号'
/
COMMENT ON COLUMN M_SCM_COMPANY.ADDRESS_1      IS '住所１'
/
COMMENT ON COLUMN M_SCM_COMPANY.ADDRESS_2      IS '住所２'
/
COMMENT ON COLUMN M_SCM_COMPANY.ADDRESS_K_1    IS '住所（カナ）１'
/
COMMENT ON COLUMN M_SCM_COMPANY.ADDRESS_K_2    IS '住所（カナ）２'
/
COMMENT ON COLUMN M_SCM_COMPANY.TEL            IS '電話番号'
/
COMMENT ON COLUMN M_SCM_COMPANY.FAX            IS 'ＦＡＸ番号'
/
