CREATE OR REPLACE VIEW V_CM_HOME_CUR (
    COMPANY_CD
   ,CTRL_CD
   ,HOME_CUR_CD
) AS
SELECT  MC.COMPANY_CD
       ,HC.CTRL_CD
       ,HC.HOME_CUR_CD
FROM    SYS_HOME_CUR HC
       ,SYS_MY_COMPANY MC
WHERE   HC.CTRL_CD = MC.CTRL_CD
/
COMMENT ON TABLE V_CM_HOME_CUR IS '邦貨ビュー'
/
COMMENT ON COLUMN V_CM_HOME_CUR.COMPANY_CD IS '会社コード'
/
COMMENT ON COLUMN V_CM_HOME_CUR.CTRL_CD IS 'SYSコントロールコード'
/
COMMENT ON COLUMN V_CM_HOME_CUR.HOME_CUR_CD IS '邦貨コード'
/

