CREATE OR REPLACE VIEW V_ODR_POINT_OUT_ITEM2
    (ITEM_CD,ITEM_NAME,DRAW_CD,SPEC,MRP_ODR_TYP,OUTSIDE_TYP,ODR_LT,FIXED_LT,
    PROP_LT,SAFETY_LT,PROP_LOT_SIZE,ODR_POINT,FIXED_ODR_QTY,SUM_STOCK_ON_HAND_QTY,
    SUM_ODR_QTY,SUM_TOTAL_RCV_QTY,ITEM_PLANT_CD,OD_PLANT_CD)
AS
Select
 M_ITEM.ITEM_CD,
 M_ITEM.ITEM_NAME,
 M_ITEM.DRAW_CD,
 M_ITEM.SPEC,
 M_ITEM.MRP_ODR_TYP,
 M_ITEM.OUTSIDE_TYP,
 M_ITEM.ODR_LT,
 M_ITEM.FIXED_LT,
 M_ITEM.PROP_LT,
 M_ITEM.SAFETY_LT,
 M_ITEM.PROP_LOT_SIZE,
 M_ITEM.ODR_POINT,
 M_ITEM.FIXED_ODR_QTY,
 NVL(T1.SUM_STOCK_ON_HAND_QTY1,0) SUM_STOCK_ON_HAND_QTY ,
 NVL(T3.SUM_ODR_QTY1,0) SUM_ODR_QTY,
 NVL(T3.SUM_TOTAL_RCV_QTY1,0) SUM_TOTAL_RCV_QTY,
 T1.PLANT_CD ITEM_PLANT_CD,
 T3.PLANT_CD OD_PLANT_CD
From
 M_ITEM,
 (Select
   T_ITEM_STOCK.ITEM_CD,
   T_ITEM_STOCK.PLANT_CD,
   NVL(Sum(T_ITEM_STOCK.STOCK_ON_HAND_QTY),0) SUM_STOCK_ON_HAND_QTY1
  From
   T_ITEM_STOCK
  Group by
   T_ITEM_STOCK.PLANT_CD, T_ITEM_STOCK.ITEM_CD
 ) T1,
 (Select
   ITEM_CD,
   PLANT_CD,
   NVL(SUM(ODR_QTY),0) SUM_ODR_QTY1,
   NVL(SUM(TOTAL_RCV_QTY),0) SUM_TOTAL_RCV_QTY1
  From
   T_OD
  Where
   T_OD.OD_TYP = 2 AND
   T_OD.ODR_STS_TYP <> 9
  Group by
   T_OD.PLANT_CD, T_OD.ITEM_CD
 ) T3
Where
 M_ITEM.ITEM_CD = T1.ITEM_CD(+) AND
 M_ITEM.ITEM_CD = T3.ITEM_CD(+) AND
 M_ITEM.MRP_ODR_TYP = 7 AND
 (M_ITEM.ODR_POINT >=
      NVL(T1.SUM_STOCK_ON_HAND_QTY1,0)
        + NVL(T3.SUM_ODR_QTY1,0)
        - NVL(T3.SUM_TOTAL_RCV_QTY1,0)
 )
/
