CREATE OR REPLACE VIEW V_OPR_INST_SLIP
    (OPR_INST_CD,WORK_ODR_CD,PLANT_CD,OD_NO,WORK_IN_PROC_CD,PROC_NAME,PROC_NO,
    JOB_ODR_CD,ITEM_CD,ITEM_NAME,WS_CD,WS_NAME,WORK_ODR_DLV_DATE,OPR_INST_START_DATE,
    OPR_INST_QTY,WORK_STS_TYP,WORK_IN_PROC_COMMENT,OPR_INST_SLIP_ISS_DATE,
    OPR_INST_SLIP_ISS_FLG,DRAW_CD,SPEC,STOCK_UNIT,PLANT_NAME,OPR_INST_SLIP_ISS_FLG_DN,
    MODIFY_COUNT)
AS
SELECT
  T_OPR_INST_SLIP.OPR_INST_CD AS OPR_INST_CD,
  T_WORK_IN_PROC_BY_PROC.WORK_ODR_CD AS WORK_ODR_CD,
  T_WORK_IN_PROC_BY_PROC.PLANT_CD AS PLANT_CD,
  T_WORK_IN_PROC_BY_PROC.OD_NO AS OD_NO,
  T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_CD AS WORK_IN_PROC_CD,
  T_WORK_IN_PROC_BY_PROC.PROC_NAME AS PROC_NAME,
  T_WORK_IN_PROC_BY_PROC.PROC_NO AS PROC_NO,
  T_OD.JOB_ODR_CD AS JOB_ODR_CD,
  T_WORK_IN_PROC_BY_PROC.ITEM_CD AS ITEM_CD,
  M_ITEM.ITEM_NAME AS ITEM_NAME,
  T_WORK_IN_PROC_BY_PROC.WS_CD AS WS_CD,
  M_WS.WS_NAME AS WS_NAME,
  T_WORK_IN_PROC_BY_PROC.WORK_ODR_DLV_DATE AS WORK_ODR_DLV_DATE,
  T_WORK_IN_PROC_BY_PROC.OPR_INST_START_DATE AS OPR_INST_START_DATE,
  T_WORK_IN_PROC_BY_PROC.OPR_INST_QTY AS OPR_INST_QTY,
  T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP AS WORK_STS_TYP,
  T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_COMMENT AS WORK_IN_PAROC_COMMENT,
  T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_DATE AS OPR_INST_SLIP_ISS_DATE,
  T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_FLG AS OPR_INST_SLIP_ISS_FLG,
  M_ITEM.DRAW_CD AS DRAW_CD,
  M_ITEM.SPEC AS SPEC,
  M_ITEM.STOCK_UNIT AS STOCK_UNIT,
  M_PLANT.PLANT_NAME AS PLANT_NAME,
  (
    SELECT
      DISPLAY_NAME
    FROM
      SYS_TYPE_VALUE
    WHERE
      NAME = 'OPR_INST_SLIP_ISS_FLG'
      AND VALUE = T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_FLG
   ) AS OPR_INST_SLIP_ISS_FLG_DN,
  T_OPR_INST_SLIP.MODIFY_COUNT
FROM
  T_OPR_INST_SLIP,
  T_WORK_IN_PROC_BY_PROC,
  T_OD,
  M_ITEM,
  M_WS,
  M_PLANT
WHERE
  T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 2 AND
  T_OPR_INST_SLIP.OPR_INST_CD = T_WORK_IN_PROC_BY_PROC.OPR_INST_CD AND
  T_WORK_IN_PROC_BY_PROC.OD_NO = T_OD.OD_NO AND
  T_WORK_IN_PROC_BY_PROC.ITEM_CD = M_ITEM.ITEM_CD AND
  T_WORK_IN_PROC_BY_PROC.WS_CD = M_WS.WS_CD(+)
  AND T_WORK_IN_PROC_BY_PROC.PLANT_CD = M_PLANT.PLANT_CD(+)
/
