CREATE OR REPLACE VIEW V_PJ_CD
  (VALUE,DISPLAY_NAME) 
AS
SELECT
	NVL(VIEW1.VALUE,'　')
	,NVL(VIEW1.DISPLAY_NAME,'　')
FROM
	(SELECT 
		NULL as VALUE
		,NULL as DISPLAY_NAME
	FROM
		DUAL
	UNION ALL
		SELECT
			SYS_TYPE_VALUE.DISPLAY_NAME
			,SYS_TYPE_VALUE.DISPLAY_NAME
		FROM
			SYS_TYPE_VALUE
		WHERE
			SYS_TYPE_VALUE.NAME = 'PJ_CD_01'
		)VIEW1
ORDER BY
	VIEW1.VALUE NULLS FIRST
/
COMMENT ON TABLE V_PJ_CD IS 'プロジェクトコードView'
/
COMMENT ON COLUMN V_PJ_CD.VALUE IS '値'
/
COMMENT ON COLUMN V_PJ_CD.DISPLAY_NAME IS '表示説明'
/
