CREATE OR REPLACE VIEW V_REGULAR_ITEM AS
SELECT T_ITEM_STOCK.PLANT_CD AS PLANT_CD,
       M_PLANT.PLANT_NAME AS PLANT_NAME,
       T_ITEM_STOCK.WH_CD AS WH_CD,
       M_WH.WH_NAME AS WH_NAME,
       T_ITEM_STOCK.ITEM_CD AS ITEM_CD,
       M_ITEM.ITEM_NAME AS ITEM_NAME,
       DECODE(M_ITEM.LOT_CTRL_FLG,1,T_LOT_NUM.LOT_NO,NULL) AS LOT_NO,
       DECODE(M_ITEM.LOT_CTRL_FLG,1,T_LOT_NUM.EXTERNAL_LOT_NO,NULL) AS EXTERNAL_LOT_NO,
       DECODE(M_ITEM.LOT_CTRL_FLG,0,TO_CHAR(T_ITEM_STOCK.STOCK_ON_HAND_QTY, 'fm99999999999990.0999'),
       1,TO_CHAR(T_LOT_NUM.STOCK_ON_HAND_QTY, 'fm99999999999990.0999')) AS STOCK_ON_HAND_QTY,
       DECODE(M_ITEM.LOT_CTRL_FLG,0,TO_CHAR(T_ITEM_STOCK.DEFECT_QTY, 'fm99999999999990.0999'),
       1,TO_CHAR(T_LOT_NUM.DEFECT_QTY, 'fm99999999999990.0999')) AS DEFECT_QTY,
       M_ITEM.STOCK_UNIT AS STOCK_UNIT,
       M_ITEM.ABC_TYP AS ABC_TYP,
       TO_CHAR(T_INV_CTRL.INV_DATE,'YYYY/MM/DD') AS INV_DATE
 FROM T_ITEM_STOCK, M_PLANT, M_ITEM, M_WH,T_INV_CTRL,
       (SELECT T_LOT_STOCK.PLANT_CD,
               T_LOT_STOCK.ITEM_CD,
               T_LOT_STOCK.LOT_NO,
               T_LOT_CTRL.EXTERNAL_LOT_NO,
               T_LOT_STOCK.WH_CD,
               T_LOT_STOCK.STOCK_ON_HAND_QTY,
               T_LOT_STOCK.DEFECT_QTY
       FROM    T_LOT_STOCK,T_LOT_CTRL
       WHERE   T_LOT_STOCK.LOT_NO = T_LOT_CTRL.LOT_NO
       AND     T_LOT_STOCK.ITEM_CD = T_LOT_CTRL.ITEM_CD) T_LOT_NUM
 WHERE T_ITEM_STOCK.WH_CD = M_WH.WH_CD
   AND T_ITEM_STOCK.ITEM_CD = M_ITEM.ITEM_CD
   AND M_ITEM.ABC_TYP <> 9
   AND M_ITEM.MRP_ODR_TYP <> 8
   AND T_ITEM_STOCK.PLANT_CD = M_PLANT.PLANT_CD
   AND T_INV_CTRL.PLANT_CD = T_ITEM_STOCK.PLANT_CD
   AND T_LOT_NUM.PLANT_CD(+) = T_ITEM_STOCK.PLANT_CD
   AND T_LOT_NUM.WH_CD(+) = T_ITEM_STOCK.WH_CD
   AND T_LOT_NUM.ITEM_CD(+) = T_ITEM_STOCK.ITEM_CD
   AND (M_ITEM.LOT_CTRL_FLG = 0 OR (M_ITEM.LOT_CTRL_FLG = 1 AND T_LOT_NUM.STOCK_ON_HAND_QTY>0))
/