CREATE OR REPLACE VIEW V_SEG_CONTENTS_1
  (VALUE,DISPLAY_NAME) 
AS
SELECT
	NVL(VIEW1.VALUE,'　')
	,NVL(VIEW1.DISPLAY_NAME,'　')
FROM
	(SELECT 
		NULL AS VALUE
		,NULL AS DISPLAY_NAME
	FROM
		DUAL
	UNION ALL
		SELECT
			SYS_TYPE_VALUE.DISPLAY_NAME
			,SYS_TYPE_VALUE.DISPLAY_NAME
		FROM
			SYS_TYPE_VALUE
		WHERE
			SYS_TYPE_VALUE.NAME = 'SEG_CONTENTS_01'
		)VIEW1
ORDER BY
	VIEW1.VALUE NULLS FIRST
/
COMMENT ON TABLE V_SEG_CONTENTS_1 IS 'セグメント1View'
/
COMMENT ON COLUMN V_SEG_CONTENTS_1.VALUE IS '値'
/
COMMENT ON COLUMN V_SEG_CONTENTS_1.DISPLAY_NAME IS '表示説明'
/
