CREATE OR REPLACE VIEW V_WORK_ISSUE_INST_LST
as
select
  T_ISSUE_INST."ISSUE_INST_CD" as "ISSUE_INST_CD",
  T_ISSUE_INST."ITEM_CD" as "ITEM_CD",
  T_ISSUE_INST."ISSUE_INST_QTY",
  T_ISSUE_INST."TOTAL_ISSUE_QTY",
  DECODE(T_ISSUE_INST."ISSUE_CMPLT_FLG", '1', 0,(T_ISSUE_INST."ISSUE_INST_QTY" - T_ISSUE_INST."TOTAL_ISSUE_QTY")) as "W_SHIP_REMAIN_QTY",
  T_ISSUE_INST."SCDL_ISSUE_DATE", 
  T_ISSUE_INST."ISSUE_CMPLT_DATE",
  T_ISSUE_INST."ISSUE_CMPLT_FLG" as "ISSUE_CMPLT_FLG",
  T_ISSUE_INST."ISSUE_TYP" as "ISSUE_TYP",
  T_ISSUE_INST."WH_CD" as "WH_CD",
  T_ISSUE_INST."WS_CD" as "WS_CD",
  T_ISSUE_INST."WORK_ODR_CD" as "WORK_ODR_CD",
  T_ISSUE_INST."WORK_IN_PROC_CD" as "WORK_IN_PROC_CD",
  T_ISSUE_INST."PUCH_ODR_CD" as "PUCH_ODR_CD",
  T_ISSUE_INST."VEND_CD" as "VEND_CD",
  T_ISSUE_INST."CONS_TYP" as "CONS_TYP",
  T_ISSUE_INST."OD_NO" as "OD_NO",
  T_ISSUE_INST."PS_EDITION" as "PS_EDITION",
  T_ISSUE_INST."ISSUE_INST_UNIT_DENOMINATOR",
  T_ISSUE_INST."ISSUE_INST_UNIT_NUMERATOR",
  T_ISSUE_INST."ISSUE_INST_COMMENT" as "ISSUE_INST_COMMENT",
  T_OD."JOB_ODR_CD" as "JOB_ODR_CD",
  M_ITEM."ITEM_NAME" as "ITEM_NAME",
  M_WH."WH_NAME" as "WH_NAME",
  M_WS."WS_NAME" as "WS_NAME",
  M_VEND_CTRL."VEND_ANAME" as "VEND_ANAME",
  T_WORK_IN_PROC_BY_PROC."PROC_NAME" as "PROC_NAME",
  T_WORK_IN_PROC_BY_ITEM."OPR_INST_CD" as "OPR_INST_CD_ITEM",
  T_WORK_IN_PROC_BY_PROC."OPR_INST_CD" as "OPR_INST_CD_PROC",
  T_ISSUE_INST."PLANT_CD" as "PLANT_CD",
  M_ITEM."STOCK_UNIT" as "STOCK_UNIT",
  (CASE WHEN T_ISSUE_INST.ISSUE_CMPLT_FLG = 0 
			AND T_ISSUE_INST.CONS_TYP = 1 
			AND T_ISSUE_INST.TOTAL_ISSUE_QTY = 0
		THEN 1
 		WHEN T_ISSUE_INST.ISSUE_CMPLT_FLG = 0 
			AND T_ISSUE_INST.CONS_TYP = 2 
			AND T_ISSUE_INST.TOTAL_ISSUE_QTY = 0
		THEN 1
 		WHEN T_ISSUE_INST.ISSUE_CMPLT_FLG = 0 
			AND T_ISSUE_INST.CONS_TYP = 0
			AND T_ISSUE_INST.TOTAL_ISSUE_QTY = 0
		THEN 2
 		WHEN T_ISSUE_INST.ISSUE_CMPLT_FLG = 0 
			AND T_ISSUE_INST.CONS_TYP = 1
			AND T_ISSUE_INST.TOTAL_ISSUE_QTY > 0
		THEN 3
 		WHEN T_ISSUE_INST.ISSUE_CMPLT_FLG = 0 
			AND T_ISSUE_INST.CONS_TYP = 2
			AND T_ISSUE_INST.TOTAL_ISSUE_QTY > 0
		THEN 3
 		WHEN T_ISSUE_INST.ISSUE_CMPLT_FLG = 0 
			AND T_ISSUE_INST.CONS_TYP = 0
			AND T_ISSUE_INST.TOTAL_ISSUE_QTY > 0
		THEN 4
 		WHEN T_ISSUE_INST.ISSUE_CMPLT_FLG = 1
		THEN 5
		ELSE NULL END ) as STATUS,
  T_ISSUE_INST."ISSUE_INST_ISS_FLG" as "ISSUE_INST_ISS_FLG",
  M_ITEM."MRP_ODR_TYP" as "MRP_ODR_TYP",
  M_ITEM."LOT_CTRL_FLG" as "LOT_CTRL_FLG",
  T_OD."JOB_ODR_DETAIL_NO" as "JOB_ODR_DETAIL_NO"
from
  T_ISSUE_INST,
  T_OD,
  M_ITEM,
  M_WH,
  M_WS,
  M_VEND_CTRL,
  T_WORK_IN_PROC_BY_PROC,
  T_WORK_IN_PROC_BY_ITEM
where
  T_ISSUE_INST.OD_NO = T_OD.OD_NO(+)
  and T_ISSUE_INST.ITEM_CD = M_ITEM.ITEM_CD(+)
  and T_ISSUE_INST.WH_CD = M_WH.WH_CD(+)
  and T_ISSUE_INST.WS_CD = M_WS.WS_CD(+)
  and T_ISSUE_INST.COMPANY_CD = M_VEND_CTRL.COMPANY_CD(+)
  and T_ISSUE_INST.VEND_CD = M_VEND_CTRL.VEND_CD(+)
  and T_ISSUE_INST.WORK_ODR_CD = T_WORK_IN_PROC_BY_PROC.WORK_ODR_CD(+)
  and T_ISSUE_INST.WORK_IN_PROC_CD = T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_CD(+)
  and T_ISSUE_INST.WORK_ODR_CD = T_WORK_IN_PROC_BY_ITEM.WORK_ODR_CD(+)
/
