CREATE OR REPLACE VIEW V_WORK_INST_PROG_LST
    (OD_NO,PROC_NO,PROC_EXPLOSION_FLG,WORK_STS_TYP,WORK_STS_TYP_DN,WORK_ODR_CD,
    OPR_INST_CD,WORK_IN_PROC_CD,PROC_NAME,WS_CD,WS_NAME,VEND_CD,VEND_ANAME,
    OUTSIDE_TYP,OPR_INST_DATE,OPR_INST_SLIP_ISS_DATE,OPR_INST_START_DATE,
    WORK_ODR_DLV_DATE,OPR_INST_QTY,TOTAL_ACPT_QTY,TOTAL_DEFECT_QTY,WORK_CMPLT_DATE,
    ACPT_INSPC_TYP)
AS
Select
/* ïiñ⁄ */
  T_WORK_IN_PROC_BY_ITEM.OD_NO as OD_NO
, NULL as PROC_NO
, T_WORK_IN_PROC_BY_ITEM.PROC_EXPLOSION_FLG as PROC_EXPLOSION_FLG
, NULL as WORK_STS_TYP
, SYS_TYPE_VALUE.DISPLAY_NAME as WORK_STS_TYP_DN
, T_WORK_IN_PROC_BY_ITEM.WORK_ODR_CD as  WORK_ODR_CD
, T_WORK_IN_PROC_BY_ITEM.OPR_INST_CD as OPR_INST_CD
, NULL as WS_CD
, NULL as PROC_NAME
, T_WORK_IN_PROC_BY_ITEM.WS_CD as PLANT_CD
, M_WS.WS_NAME as PLANT_CD
, NULL as VEND_CD
, NULL as VEND_ANAME
, 1 as OUTSIDE_TYP /* ì‡çÏå≈íË */
, T_WORK_IN_PROC_BY_ITEM.OPR_INST_DATE as OPR_INST_DATE
, T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_DATE as OPR_INST_SLIP_ISS_DATE
, T_WORK_IN_PROC_BY_ITEM.OPR_INST_START_DATE as OPR_INST_START_DATE
, T_WORK_IN_PROC_BY_ITEM.WORK_ODR_DLV_DATE as WORK_ODR_DLV_DATE
, T_WORK_IN_PROC_BY_ITEM.OPR_INST_QTY as OPR_INST_QTY
, NVL(SUM_OPR_RSLT.TOTAL_ACPT_QTY,0) as TOTAL_ACPT_QTY
, NVL(SUM_OPR_RSLT.TOTAL_DEFECT_QTY,0) as TOTAL_DEFECT_QTY
, T_WORK_IN_PROC_BY_ITEM.WORK_CMPLT_DATE as WORK_CMPLT_DATE
, NULL as ACPT_INSPC_TYP
From
  T_WORK_IN_PROC_BY_ITEM
, M_WS
, ( Select
      OPR_INST_CD
    , Sum(T_OPR_RSLT.ACPT_QTY) TOTAL_ACPT_QTY
    , Sum(T_OPR_RSLT.DEFECT_QTY) TOTAL_DEFECT_QTY
    From T_OPR_RSLT
    Group by OPR_INST_CD
  ) SUM_OPR_RSLT
, T_OPR_INST_SLIP
, SYS_TYPE_VALUE
Where
  T_WORK_IN_PROC_BY_ITEM.WS_CD = M_WS.WS_CD(+)
  and T_WORK_IN_PROC_BY_ITEM.OPR_INST_CD = SUM_OPR_RSLT.OPR_INST_CD(+)
  and T_WORK_IN_PROC_BY_ITEM.PROC_EXPLOSION_FLG = '0' /* ñ¢ìWäJ */
  and T_WORK_IN_PROC_BY_ITEM.OPR_RSLT_TYP = '2' /* çÏã∆éwé¶é¿ê— */
  and T_WORK_IN_PROC_BY_ITEM.OPR_INST_CD = T_OPR_INST_SLIP.OPR_INST_CD(+)
  and SYS_TYPE_VALUE.NAME = 'PROC_EXPLOSION_FLG'
  and T_WORK_IN_PROC_BY_ITEM.PROC_EXPLOSION_FLG = SYS_TYPE_VALUE.VALUE(+)
union
Select
/* ånóÒ */
  T_WORK_IN_PROC_BY_PROC.OD_NO as OD_NO
, T_WORK_IN_PROC_BY_PROC.PROC_NO as PROC_NO
, NULL as PROC_EXPLOSION_FLG
, T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP as WORK_STS_TYP
, SYS_TYPE_VALUE.DISPLAY_NAME as WORK_STS_TYP_DN
, T_WORK_IN_PROC_BY_PROC.WORK_ODR_CD as WORK_ODR_CD
, T_WORK_IN_PROC_BY_PROC.OPR_INST_CD as OPR_INST_CD
, T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_CD as WORK_IN_PROC_CD
, T_WORK_IN_PROC_BY_PROC.PROC_NAME as PROC_NAME
, T_WORK_IN_PROC_BY_PROC.WS_CD as WS_CD
, M_WS.WS_NAME as WS_NAME
, T_WORK_IN_PROC_BY_PROC.VEND_CD as VEND_CD
, M_VEND_CTRL.VEND_ANAME as VEND_ANAME
, T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP as OUTSIDE_TYP
, T_WORK_IN_PROC_BY_PROC.OPR_INST_DATE as OPR_INST_DATE
, T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_DATE as OPR_INST_SLIP_ISS_DATE
, T_WORK_IN_PROC_BY_PROC.OPR_INST_START_DATE as OPR_INST_START_DATE
, T_WORK_IN_PROC_BY_PROC.WORK_ODR_DLV_DATE as WORK_ODR_DLV_DATE
, T_WORK_IN_PROC_BY_PROC.OPR_INST_QTY as OPR_INST_QTY
, NVL(SUM_OPR_RSLT.TOTAL_ACPT_QTY,0) as TOTAL_ACPT_QTY
, NVL(SUM_OPR_RSLT.TOTAL_DEFECT_QTY,0) as TOTAL_DEFECT_QTY
, T_WORK_IN_PROC_BY_PROC.WORK_CMPLT_DATE as WORK_CMPLT_DATE
, T_WORK_IN_PROC_BY_PROC.ACPT_INSPC_TYP as ACPT_INSPC_TYP
From
  T_WORK_IN_PROC_BY_PROC
, M_WS
, M_VEND_CTRL
, ( Select
      OPR_INST_CD
    , Sum(T_OPR_RSLT.ACPT_QTY) TOTAL_ACPT_QTY
    , Sum(T_OPR_RSLT.DEFECT_QTY) TOTAL_DEFECT_QTY
    From T_OPR_RSLT
    Group by OPR_INST_CD
  ) SUM_OPR_RSLT
, T_OPR_INST_SLIP
, SYS_TYPE_VALUE
Where
  T_WORK_IN_PROC_BY_PROC.WS_CD = M_WS.WS_CD(+)
  and T_WORK_IN_PROC_BY_PROC.VEND_CD = M_VEND_CTRL.VEND_CD(+)
  and T_WORK_IN_PROC_BY_PROC.OPR_INST_CD = SUM_OPR_RSLT.OPR_INST_CD(+)
  and T_WORK_IN_PROC_BY_PROC.OPR_INST_CD = T_OPR_INST_SLIP.OPR_INST_CD(+)
  and SYS_TYPE_VALUE.NAME = 'WORK_STS_TYP'
  and T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = SYS_TYPE_VALUE.VALUE(+)
/
