CREATE OR REPLACE VIEW V_WORK_ODR_LST
    (OPR_INST_CD,WORK_ODR_CD,PLANT_CD,OD_NO,WORK_IN_PROC_CD,PROC_NAME,PROC_NO,
    JOB_ODR_CD,ITEM_CD,ITEM_NAME,WS_CD,WS_NAME,VEND_CD,VEND_NAME,VEND_ANAME,
    WORK_ODR_DLV_DATE,OPR_INST_START_DATE,OPR_INST_QTY,WORK_STS_TYP,OPR_RSLT_TYP,
    WORK_IN_PROC_COMMENT,OUTSIDE_TYP,MODIFY_COUNT)
AS
Select
 T_OPR_INST_SLIP.OPR_INST_CD as OPR_INST_CD,
 T_WORK_IN_PROC_BY_PROC.WORK_ODR_CD as WORK_ODR_CD,
 T_WORK_IN_PROC_BY_PROC.PLANT_CD as PLANT_CD,
 T_WORK_IN_PROC_BY_PROC.OD_NO as OD_NO,
 T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_CD as WORK_IN_PROC_CD,
 T_WORK_IN_PROC_BY_PROC.PROC_NAME as PROC_NAME,
 T_WORK_IN_PROC_BY_PROC.PROC_NO as PROC_NO,
 T_OD.JOB_ODR_CD as JOB_ODR_CD,
 T_WORK_IN_PROC_BY_PROC.ITEM_CD as ITEM_CD,
 M_ITEM.ITEM_NAME as ITEM_NAME,
 T_WORK_IN_PROC_BY_PROC.WS_CD as WS_CD,
 M_WS.WS_NAME as WS_NAME,
 T_WORK_IN_PROC_BY_PROC.VEND_CD as VEND_CD,
 M_VEND_CTRL.VEND_NAME as VEND_NAME,
 M_VEND_CTRL.VEND_ANAME as VEND_ANAME,
 T_WORK_IN_PROC_BY_PROC.WORK_ODR_DLV_DATE as WORK_ODR_DLV_DATE,
 T_WORK_IN_PROC_BY_PROC.OPR_INST_START_DATE as OPR_INST_START_DATE,
 T_WORK_IN_PROC_BY_PROC.OPR_INST_QTY as OPR_INST_QTY,
 T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP as WORK_STS_TYP,
 2 as OPR_RSLT_TYP,
 T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_COMMENT as WORK_IN_PAROC_COMMENT,
 T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP as OUTSIDE_TYP,
 T_WORK_IN_PROC_BY_PROC.MODIFY_COUNT as MODIFY_COUNT
From
 T_OPR_INST_SLIP,
 T_WORK_IN_PROC_BY_PROC,
 T_OD,
 M_ITEM,
 M_WS,
 M_VEND_CTRL
Where
 T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 1 and
 T_OPR_INST_SLIP.OPR_INST_CD(+) = T_WORK_IN_PROC_BY_PROC.OPR_INST_CD and
 T_WORK_IN_PROC_BY_PROC.OD_NO = T_OD.OD_NO and
 T_WORK_IN_PROC_BY_PROC.ITEM_CD = M_ITEM.ITEM_CD and
 T_WORK_IN_PROC_BY_PROC.WS_CD = M_WS.WS_CD(+) and
 T_WORK_IN_PROC_BY_PROC.COMPANY_CD = M_VEND_CTRL.COMPANY_CD(+) and
 T_WORK_IN_PROC_BY_PROC.VEND_CD = M_VEND_CTRL.VEND_CD(+)
union
Select
 T_OPR_INST_SLIP.OPR_INST_CD as OPR_INST_CD,
 T_WORK_IN_PROC_BY_ITEM.WORK_ODR_CD as WORK_ODR_CD,
 T_WORK_IN_PROC_BY_ITEM.PLANT_CD as PLANT_CD,
 T_WORK_IN_PROC_BY_ITEM.OD_NO as OD_NO,
 NULL as WORK_IN_PROC_CD,
 NULL as PROC_NAME,
 0 as PROC_NO,
 T_OD.JOB_ODR_CD as JOB_ODR_CD,
 T_WORK_IN_PROC_BY_ITEM.ITEM_CD as ITEM_CD,
 M_ITEM.ITEM_NAME as ITEM_NAME,
 T_WORK_IN_PROC_BY_ITEM.WS_CD as WS_CD,
 M_WS.WS_NAME as WS_NAME,
 NULL as VEND_CD,
 NULL as VEND_NAME,
 NULL as VEND_ANAME,
 T_WORK_IN_PROC_BY_ITEM.WORK_ODR_DLV_DATE as WORK_ODR_DLV_DATE,
 T_WORK_IN_PROC_BY_ITEM.OPR_INST_START_DATE as OPR_INST_START_DATE,
 T_WORK_IN_PROC_BY_ITEM.OPR_INST_QTY as OPR_INST_QTY,
 T_WORK_IN_PROC_BY_ITEM.WORK_STS_TYP as WORK_STS_TYP,
 T_WORK_IN_PROC_BY_ITEM.OPR_RSLT_TYP as OPR_RSLT_TYP,
 T_WORK_IN_PROC_BY_ITEM.WORK_IN_PROC_COMMENT as WORK_IN_PROC_COMMENT,
 1 as OUTSIDE_TYP,
 T_WORK_IN_PROC_BY_ITEM.MODIFY_COUNT as MODIFY_COUNT
From
 T_OPR_INST_SLIP,
 T_WORK_IN_PROC_BY_ITEM,
 T_OD,
 M_ITEM,
 M_WS
Where
 T_WORK_IN_PROC_BY_ITEM.WORK_STS_TYP = 1 and
 T_OPR_INST_SLIP.OPR_INST_CD_GNR_TYP = 1 and
 T_OPR_INST_SLIP.OPR_INST_CD = T_WORK_IN_PROC_BY_ITEM.OPR_INST_CD and
 T_WORK_IN_PROC_BY_ITEM.OD_NO = T_OD.OD_NO and
 T_WORK_IN_PROC_BY_ITEM.ITEM_CD = M_ITEM.ITEM_CD and
 T_WORK_IN_PROC_BY_ITEM.WS_CD = M_WS.WS_CD(+)
/
