CREATE OR REPLACE VIEW V_WORK_IN_PROC_LST
	(PLANT_CD, WORK_ODR_CD, PROC_NO, WORK_IN_PROC_CD, PROC_NAME, WORK_ODR_DLV_DATE, 
	OPR_INST_START_DATE, OPR_INST_CD, PUCH_ODR_CD, OPR_INST_DATE, 
	OPR_INST_SLIP_ISS_DATE, OPR_INST_QTY, SUM_ACPT_QTY, SUM_DEFECT_QTY, 
	STOCK_UNIT, WORK_STS_TYP, WORK_STS_NAME, WORK_CMPLT_DATE, 
	ITEM_CD, ITEM_NAME, DRAW_CD, SPEC, MRP_ODR_TYP, JOB_ODR_CD, JOB_ODR_CANCEL_NO, 
	OPR_RSLT_TYP, OUTSIDE_TYP, ACPT_INSPC_TYP, WS_CD, WS_NAME, VEND_CD, 
	VEND_ANAME,TABLE_NAME,OPR_INST_SLIP_ISS_FLG,WORK_STATUS) 
AS 
select 
		T_WORK_IN_PROC_BY_ITEM.PLANT_CD,			--  5.[品目別仕掛].工場コード
		T_WORK_IN_PROC_BY_ITEM.WORK_ODR_CD,			--  6.[品目別仕掛].作業計画番号
		null as PROC_NO,							--  7.仕掛作業系列番号(NULL)
		null as WORK_IN_PROC_CD,					--  8.仕掛作業コード(NULL)
		null as PROC_NAME,							--  9.仕掛作業名(NULL)
		T_WORK_IN_PROC_BY_ITEM.WORK_ODR_DLV_DATE,	-- 10.[品目別仕掛].作業製造納期
		T_WORK_IN_PROC_BY_ITEM.OPR_INST_START_DATE,	-- 11.[品目別仕掛].作業製造着手日
		T_WORK_IN_PROC_BY_ITEM.OPR_INST_CD,			-- 12.[品目別仕掛].作業指示番号
		null as PUCH_ODR_CD,						-- 13.発注番号(NULL)
		T_WORK_IN_PROC_BY_ITEM.OPR_INST_DATE,		-- 14.[品目別仕掛].作業指示日
		T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_DATE,		-- 15.[作業指示伝票].作業指示伝票発行日
		T_WORK_IN_PROC_BY_ITEM.OPR_INST_QTY,		-- 16.[品目別仕掛].作業指示数
		T_OPR_RSLT.SUM_ACPT_QTY,					-- 17.[作業実績].良品累計数
		T_OPR_RSLT.SUM_DEFECT_QTY,					-- 18.[作業実績].不良累計数
		M_ITEM.STOCK_UNIT,							-- 19.[品目Ｍ].計量単位
		T_WORK_IN_PROC_BY_ITEM.WORK_STS_TYP,		-- 条件で使用.作業状態区分
		WORK_STS_TBL.DISPLAY_NAME as WORK_STS_NAME,	-- 20.[品目別仕掛].作業状態区分名
		T_WORK_IN_PROC_BY_ITEM.WORK_CMPLT_DATE,		-- 21.[品目別仕掛].作業完了日
		T_WORK_IN_PROC_BY_ITEM.ITEM_CD,				-- 22.[品目別仕掛].品目番号
		M_ITEM.ITEM_NAME,							-- 23.[品目Ｍ].品目名
		M_ITEM.DRAW_CD,								-- 24.[品目Ｍ].図面番号
		M_ITEM.SPEC,								-- 25.[品目Ｍ].規格
		MRP_ODR_TBL.VALUE as MRP_ODR_TYP,	-- 26.[所要量].品目手配区分
		T_OD.JOB_ODR_CD,							-- 27.[所要量].製番
		T_OD.JOB_ODR_CANCEL_NO,						-- 28.[所要量].製番取消発生番号
		OPR_RSLT_TBL.VALUE as OPR_RSLT_TYP,	-- 条件で使用.品目別作業実績区分
		OUTSIDE_TBL.VALUE as OUTSIDE_TYP,	-- 29.仕掛内外作区分
		null as ACPT_INSPC_TYP,						-- 30.受入検査区分
		T_WORK_IN_PROC_BY_ITEM.WS_CD,				-- 31.[品目別仕掛].作業区コード
		M_WS.WS_NAME,								-- 32.[作業区].作業区名
		null as VEND_CD,							-- 33.取引先コード
		null as VEND_ANAME,							-- 34.取引先略称
		'T_WORK_IN_PROC_BY_ITEM' as TABLE_NAME,		-- 35.品目別仕掛のレコードであることを表す
		T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_FLG,
		(CASE  WHEN T_WORK_IN_PROC_BY_ITEM.WORK_STS_TYP = 1 THEN 1
		ELSE NULL END) AS WORK_STATUS				-- 36.ステータスの判定
	from T_OPR_INST_SLIP, 			-- 作業指示票
		T_WORK_IN_PROC_BY_ITEM, 	-- 品目別仕掛
		M_ITEM, 					-- 品目Ｍ
		T_OD, 						-- 所要量
		M_WS,						-- 作業区
		(select OPR_INST_CD, sum(nvl(ACPT_QTY, 0)) as SUM_ACPT_QTY, sum(nvl(DEFECT_QTY, 0)) as SUM_DEFECT_QTY
			 from T_OPR_RSLT group by OPR_INST_CD) T_OPR_RSLT,		-- 作業実績
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'WORK_STS_TYP') WORK_STS_TBL,
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'MRP_ODR_TYP') MRP_ODR_TBL,
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'OPR_RSLT_TYP' and VALUE = 1) OPR_RSLT_TBL,
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'OUTSIDE_TYP' and VALUE = 1) OUTSIDE_TBL
	where MRP_ODR_TBL.VALUE(+) = T_OD.MRP_ODR_TYP
	 and  WORK_STS_TBL.VALUE(+) = T_WORK_IN_PROC_BY_ITEM.WORK_STS_TYP
	 and  T_WORK_IN_PROC_BY_ITEM.WS_CD = M_WS.WS_CD(+)
	 and  T_WORK_IN_PROC_BY_ITEM.OD_NO = T_OD.OD_NO(+)
	 and  T_WORK_IN_PROC_BY_ITEM.ITEM_CD = M_ITEM.ITEM_CD(+)
	 and  T_WORK_IN_PROC_BY_ITEM.OPR_INST_CD = T_OPR_RSLT.OPR_INST_CD(+)
	 and  T_WORK_IN_PROC_BY_ITEM.OPR_INST_CD = T_OPR_INST_SLIP.OPR_INST_CD(+)
	 and  T_WORK_IN_PROC_BY_ITEM.OPR_RSLT_TYP = 2			-- [品目別仕掛].品目別作業実績区分=2:作業指示実績
	 and  T_WORK_IN_PROC_BY_ITEM.PROC_EXPLOSION_FLG = 0		-- [品目別仕掛].作業系列展開済みフラグ=0:未展開
	 and  T_WORK_IN_PROC_BY_ITEM.OPR_RSLT_TYP <> 1			-- [品目別仕掛].品目別作業実績区分<>1 
	UNION
	select 
		T_WORK_IN_PROC_BY_PROC.PLANT_CD,			--  5.[作業系列別仕掛].工場コード
		T_WORK_IN_PROC_BY_PROC.WORK_ODR_CD,			--  6.[作業系列別仕掛].作業計画番号
		T_WORK_IN_PROC_BY_PROC.PROC_NO,				--  7.[作業系列別仕掛].仕掛作業系列番号
		T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_CD,		--  8.[作業系列別仕掛].仕掛作業コード
		T_WORK_IN_PROC_BY_PROC.PROC_NAME,			--  9.[作業系列別仕掛].仕掛作業名
		T_WORK_IN_PROC_BY_PROC.WORK_ODR_DLV_DATE,	-- 10.[作業系列別仕掛].作業系列別製造納期
		T_WORK_IN_PROC_BY_PROC.OPR_INST_START_DATE,	-- 11.[作業系列別仕掛].作業系列別製造着手日
		T_WORK_IN_PROC_BY_PROC.OPR_INST_CD,			-- 12.[作業系列別仕掛].作業指示番号
		T_RLSD_PUCH_ODR.PUCH_ODR_CD,				-- 13.[発注残].発注番号
		T_WORK_IN_PROC_BY_PROC.OPR_INST_DATE,		-- 14.[作業系列別仕掛].作業指示日
		T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_DATE,		-- 15.[作業指示伝票].作業指示伝票発行日
		T_WORK_IN_PROC_BY_PROC.OPR_INST_QTY,		-- 16.[作業系列別仕掛].作業指示数
		T_OPR_RSLT.SUM_ACPT_QTY,					-- 17.良品累計数
		T_OPR_RSLT.SUM_DEFECT_QTY,					-- 18.不良累計数
		M_ITEM.STOCK_UNIT,							-- 19.[品目Ｍ].計量単位
		T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP,		-- 条件で使用.作業状態区分
		WORK_STS_TBL.DISPLAY_NAME as WORK_STS_NAME,	-- 20.[作業系列別仕掛].作業状態区分名
		T_WORK_IN_PROC_BY_PROC.WORK_CMPLT_DATE,		-- 21.[作業系列別仕掛].作業完了日
		T_WORK_IN_PROC_BY_PROC.ITEM_CD,				-- 22.[品目Ｍ].品目番号
		M_ITEM.ITEM_NAME,							-- 23.[品目Ｍ].品目名
		M_ITEM.DRAW_CD,								-- 24.[品目Ｍ].図面番号
		M_ITEM.SPEC,								-- 25.[品目Ｍ].規格
		MRP_ODR_TBL.VALUE as MRP_ODR_TYP,	-- 26.[所要量].品目手配区分
		T_OD.JOB_ODR_CD,							-- 27.[所要量].製番
		T_OD.JOB_ODR_CANCEL_NO,						-- 28.[所要量].製番取消発生番号
		OPR_RSLT_TBL.VALUE as OPR_RSLT_TYP,	-- 条件で使用.品目別作業実績区分
		OUTSIDE_TBL.VALUE as OUTSIDE_TYP,	-- 29.仕掛内外作区分
		decode(T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP,1,null,ACPT_INSPC_TBL.VALUE) as ACPT_INSPC_TYP,		-- 30.受入検査区分
		T_WORK_IN_PROC_BY_PROC.WS_CD,				-- 31.[作業系列別仕掛].作業区コード
		M_WS.WS_NAME,								-- 32.[作業区].作業区名
		T_WORK_IN_PROC_BY_PROC.VEND_CD,				-- 33.[作業系列別仕掛].取引先コード
		M_VEND_CTRL.VEND_ANAME,						-- 34.[取引先].取引先略称
		'T_WORK_IN_PROC_BY_PROC' as TABLE_NAME,		-- 35.作業系列別仕掛のレコードであることを表す
		T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_FLG,
		(CASE  WHEN T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 1 THEN 2
			WHEN T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 2 AND T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP = 2 AND T_RLSD_PUCH_ODR.PUCH_ODR_STS_TYP = 2 AND T_RLSD_PUCH_ODR.PUCH_ODR_INST_SLIP_ISS_FLG = 0 AND T_RLSD_PUCH_ODR.ODR_CANCEL_SLIP_ISS_FLG = 0 AND T_ACPT_RSLT.PUCH_ODR_CD IS NULL THEN 3
			WHEN T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 2 AND T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP = 1 AND T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_FLG =0 AND T_OPR_RSLT.OPR_INST_CD IS NULL THEN 3
			WHEN T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 2 AND T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP = 1 AND T_OPR_INST_SLIP.OPR_INST_SLIP_ISS_FLG = 1 AND T_OPR_RSLT.OPR_INST_CD IS NULL THEN 4
			WHEN T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 2 AND T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP = 1 AND T_OPR_RSLT.OPR_INST_CD IS NOT NULL THEN 5
			WHEN T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP = 9 THEN 6
		ELSE NULL END) AS WORK_STATUS				-- 36.ステータスの判定
	from T_OPR_INST_SLIP, 			-- 作業指示票
		T_WORK_IN_PROC_BY_PROC, 	-- 作業系列別仕掛
		M_ITEM, 					-- 品目Ｍ
		T_OD, 						-- 所要量
		M_WS,						-- 作業区
		M_VEND_CTRL,				-- 取引先Ｍ
		(select OPR_INST_CD, sum(nvl(ACPT_QTY,0)) as SUM_ACPT_QTY, sum(nvl(DEFECT_QTY, 0)) as SUM_DEFECT_QTY
			 from T_OPR_RSLT group by OPR_INST_CD) T_OPR_RSLT,		-- 作業実績
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'WORK_STS_TYP') WORK_STS_TBL,
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'MRP_ODR_TYP') MRP_ODR_TBL,
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'OPR_RSLT_TYP' and VALUE = 2) OPR_RSLT_TBL,
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'OUTSIDE_TYP') OUTSIDE_TBL,
		(select VALUE, DISPLAY_NAME from SYS_TYPE_VALUE where NAME = 'ACPT_INSPC_TYP') ACPT_INSPC_TBL,
		T_RLSD_PUCH_ODR,			-- 発注残
		T_ACPT_RSLT					-- 受入実績
	where OUTSIDE_TBL.VALUE(+) = T_WORK_IN_PROC_BY_PROC.OUTSIDE_TYP
	 and  MRP_ODR_TBL.VALUE(+) = T_OD.MRP_ODR_TYP
	 and  WORK_STS_TBL.VALUE(+) = T_WORK_IN_PROC_BY_PROC.WORK_STS_TYP
	 and  ACPT_INSPC_TBL.VALUE(+) = T_WORK_IN_PROC_BY_PROC.ACPT_INSPC_TYP
	 and  T_WORK_IN_PROC_BY_PROC.VEND_CD = M_VEND_CTRL.VEND_CD(+)
	 and  T_WORK_IN_PROC_BY_PROC.WS_CD = M_WS.WS_CD(+)
	 and  T_WORK_IN_PROC_BY_PROC.OD_NO = T_OD.OD_NO(+)
	 and  T_WORK_IN_PROC_BY_PROC.ITEM_CD = M_ITEM.ITEM_CD(+)
	 and  T_WORK_IN_PROC_BY_PROC.OPR_INST_CD = T_OPR_RSLT.OPR_INST_CD(+)
	 and  T_WORK_IN_PROC_BY_PROC.OPR_INST_CD = T_OPR_INST_SLIP.OPR_INST_CD(+)
	 and  T_WORK_IN_PROC_BY_PROC.WORK_ODR_CD = T_RLSD_PUCH_ODR.WORK_ODR_CD(+)			-- [作業系列別仕掛].作業計画番号 = [発注残].作業計画番号
	 and  T_WORK_IN_PROC_BY_PROC.WORK_IN_PROC_CD = T_RLSD_PUCH_ODR.WORK_IN_PROC_CD(+)	-- [作業系列別仕掛].仕掛作業コード = [発注残].仕掛作業コード
   and  T_ACPT_RSLT.PUCH_ODR_CD(+) = T_RLSD_PUCH_ODR.PUCH_ODR_CD 
/

