---
-------------------------------------------------------------
-- get_onerousMCJa.sql
-------------------------------------------------------------*/
SET HEADING OFF
SET FEEDBAC OFF
SET PAGES 0
SET TERMOUT OFF
SET TRIMSPOOL ON
SET TAB OFF
SET EMBEDDED OFF
TTITLE OFF
BTITLE OFF
SET LINESIZE 799

SPOOL sys_parameter_onerousMCJa.csv
 SELECT NAME ||','||
 VALUE ||','||
 DESCRIPTION ||','||
 DESCRIPTION_EN ||','||
 CHANGEABLE_TYP FROM SYS_PARAMETER WHERE
NAME IN (SELECT PLANT_CD || '_ONEROUS_CONS_INV_TYP' FROM M_PLANT);

 SELECT NAME ||','||
 VALUE ||','||
 DESCRIPTION ||','||
 DESCRIPTION_EN ||','||
 CHANGEABLE_TYP FROM SYS_PARAMETER WHERE
    NAME IN (SELECT 'APR_USER_MST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_UNIT_COST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_PUCH_UNIT_COST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_CONS_UNIT_COST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_SBCNT_UNIT_COST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_VEND_CTRL_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_CUST_STL_CTRL_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_CUST_STL_CTRL_BAT_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_BANK_ACCT_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_ARAP_CUST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_AUTO_JNL_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_COMPANY_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_EXCH_RATE_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_USER_COMPANY_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_USER_CTRL_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_CUST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_CUST_DESINATED_DLV_LOC_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_BANK_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_REVAL_EXCH_RATE_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_ACCT_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_PAY_PATTERN_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_PAY_METHOD_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_BANK_FEE_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_ARAP_VEND_CTRL_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_ARAP_VEND_PAY_CTRL_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_INV_CTRL_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_INSPC_IF_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_PUR_INST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_SALES_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_ODR_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_SOURCE_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_DLV_LOC_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_CUST_DESINATED_DLV_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_MPSA_CUST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_SALES_UNIT_COST_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_JA_UNCNFM_ODR_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_JA_ODR_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_SALES_APPER_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_ITEM_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'APR_CUST_COMB_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'REQUEST_APPR_SAME_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'HISTORY_FOR_APPR_' || COMPANY_CD FROM M_SCM_COMPANY)
 OR NAME IN (SELECT 'CM_ACCOUNTING_IF_BAT_PATH_' || COMPANY_CD FROM M_SCM_COMPANY);

SPOOL OFF
EXIT
